[build]
  # Diretório onde o Netlify vai procurar os arquivos construídos
  publish = "build"
  
  # Comando para construir o projeto
  command = "npm run build"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"
  
  # Variáveis de ambiente
  REACT_APP_APP_NAME = "GMBiblioteca"
  REACT_APP_VERSION = "1.0.0"
  REACT_APP_ENVIRONMENT = "production"

# Redirecionamentos para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para arquivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para outros arquivos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
